spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=CustomDB
    username: sa
    password: Str0ngPa$$w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect



shorturl:
  length: 6